[package]
name = "toml-file"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]
reporting = ["dep:codespan-reporting"]

[dependencies]
codespan-reporting = { version = "0.11", optional = true }
identconv = "0.2"
serde = { version = "1.0", optional = true }
smallvec = "1.13"
